# TESTING Voting and Stacking

In [1]:
from si.ensemble.StackingClassifier import StackingClassifier
from si.ensemble.Votingclassifier import VotingClassifier
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from si.read_csv import read_csv
from sklearn.preprocessing import StandardScaler
from si.model_selection.split import train_test_split
from si.neighbors.knn_classifier import KNNClassifier
from si.linear_model.logistic_regression import LogisticRegression

In [7]:
dataset= read_csv("C:/Users/André Silva/SI/breast-bin.csv", sep=",")
from sklearn.preprocessing import StandardScaler
dataset.X = StandardScaler().fit_transform(dataset.X)
dataset.X

array([[ 0.20885295, -0.69912815, -0.74242297, ..., -1.0000359 ,
        -0.61132565, -0.34418721],
       [-0.8578253 , -0.69912815, -0.74242297, ..., -0.58991542,
        -0.61132565, -0.34418721],
       [-0.8578253 , -0.69912815, -0.74242297, ..., -0.17979494,
        -0.61132565, -0.34418721],
       ...,
       [ 0.20885295, -0.37139715, -0.40592217, ..., -1.0000359 ,
        -0.61132565,  0.23892607],
       [-0.8578253 , -0.04366616, -0.40592217, ..., -0.17979494,
        -0.61132565, -0.34418721],
       [ 0.91997179,  0.93952681,  0.94008103, ...,  1.46068699,
        -0.61132565, -0.34418721]])

In [3]:
train_dataset, test_dataset = train_test_split(dataset,0.20)
test_dataset.y

array([ 274,   30,   22,  915,   16,  326,   72,    6, 1144,  208,   65,
        130,   52,   45,   35,   36,   51,   31,  100,  132,   50,   60,
        110,   18,   11,   50,   69,   27,   19,   41,  248,   32,   45,
         26,   16,   26,   67,  465,   38,   17,  307], dtype=int64)

In [4]:
# voting classifier

knn = KNNClassifier(3)
lg = LogisticRegression(l2_penalty=1, alpha=0.001, max_iter=1000)

# initialize the Voting classifier
voting = VotingClassifier([knn, lg])

voting.fit(train_dataset)

In [5]:
voting.predict(test_dataset)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [6]:
voting.score(train_dataset)

0.0