# TESTING NN WITH DATASETS

In [1]:
from si.neural_netwoks.layer import *
from si.neural_netwoks.nn import NN
from si.data.dataset1 import Dataset
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from si.read_csv import read_csv
from si.model_selection.split import train_test_split
from si.metrics.cross_entropy import cross_entropy_derivate,cross_entropy
from si.metrics.accuracy import accuracy
from si.metrics.mse import mse

In [2]:
dataset2= read_csv("C:/Users/André Silva/SI/datasets/breast-bin.csv", sep=",")
dataset2.X= StandardScaler().fit_transform(dataset2.X)
train,test= train_test_split(dataset2, test_size=0.30)
train.y

array([0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1.,
       1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 1.

In [3]:
train.X

array([[-1.21338472, -0.69912815, -0.74242297, ..., -1.0000359 ,
        -0.61132565, -0.34418721],
       [-1.21338472, -0.69912815, -0.74242297, ..., -1.0000359 ,
        -0.61132565, -0.34418721],
       [ 1.63109063,  0.93952681,  1.94958343, ..., -0.58991542,
         2.00850737,  4.90383236],
       ...,
       [-1.21338472, -0.69912815, -0.40592217, ..., -0.17979494,
        -0.61132565, -0.34418721],
       [-0.50226589, -0.69912815, -0.74242297, ..., -1.0000359 ,
        -0.61132565, -0.34418721],
       [ 0.56441237,  0.61179582,  0.26707943, ...,  1.46068699,
         1.68102824,  0.82203936]])

In [4]:
n=train.X.shape[1]
n

9

In [5]:
#Create a entry level layer

l1= Dense(input_size=n,output_size=n)
l2= Dense(input_size=n,output_size=n)
l3= Dense(input_size=n,output_size=1)

l1_sg= ReLUActivation()
l2_sg= ReLUActivation()
l3_sg= SigmoidActivation()

In [6]:
nn_model= NN(layers=[l1,l1_sg,l2,l2_sg,l3,l3_sg],loss_derivate=cross_entropy_derivate,loss_function=cross_entropy)

In [7]:
nn_model.fit(dataset=train)

Epoch 1/1000-cost=0.0015
Epoch 2/1000-cost=0.0208
Epoch 3/1000-cost=0.0278
Epoch 4/1000-cost=0.0325
Epoch 5/1000-cost=0.0341
Epoch 6/1000-cost=0.0352
Epoch 7/1000-cost=0.0360
Epoch 8/1000-cost=0.0368
Epoch 9/1000-cost=0.0375
Epoch 10/1000-cost=0.0382
Epoch 11/1000-cost=0.0386
Epoch 12/1000-cost=0.0388
Epoch 13/1000-cost=0.0391
Epoch 14/1000-cost=0.0392
Epoch 15/1000-cost=0.0387
Epoch 16/1000-cost=0.0380
Epoch 17/1000-cost=0.0374
Epoch 18/1000-cost=0.0369
Epoch 19/1000-cost=0.0365
Epoch 20/1000-cost=0.0362
Epoch 21/1000-cost=0.0361
Epoch 22/1000-cost=0.0361
Epoch 23/1000-cost=0.0363
Epoch 24/1000-cost=0.0363
Epoch 25/1000-cost=0.0361
Epoch 26/1000-cost=0.0358
Epoch 27/1000-cost=0.0353
Epoch 28/1000-cost=0.0348
Epoch 29/1000-cost=0.0344
Epoch 30/1000-cost=0.0341
Epoch 31/1000-cost=0.0338
Epoch 32/1000-cost=0.0336
Epoch 33/1000-cost=0.0334
Epoch 34/1000-cost=0.0333
Epoch 35/1000-cost=0.0332
Epoch 36/1000-cost=0.0331
Epoch 37/1000-cost=0.0331
Epoch 38/1000-cost=0.0331
Epoch 39/1000-cost=0.

In [8]:
predict=nn_model.predict(dataset=test).reshape(1,-1)

In [9]:
print(predict)

[[1.00000000e+00 1.00000000e+00 1.48209762e-02 4.09763965e-05
  3.06190595e-04 1.30366571e-05 1.00000000e+00 1.10883028e-03
  2.92957831e-05 1.00000000e+00 3.68996131e-04 1.00000000e+00
  9.99999952e-01 1.00000000e+00 1.73104602e-02 3.39328874e-05
  3.06190595e-04 2.48981393e-02 1.00000000e+00 1.39961404e-04
  1.95398200e-05 1.00000000e+00 8.14342082e-05 1.00000000e+00
  1.00000000e+00 1.81696647e-01 4.16405655e-06 4.70661059e-04
  7.22123492e-05 2.61268760e-04 1.00000000e+00 1.17747837e-02
  1.00000000e+00 5.39031063e-05 1.48049506e-04 4.87435846e-05
  1.70904710e-05 8.14342082e-05 1.00000000e+00 1.00000000e+00
  1.09938622e-02 3.39328874e-05 1.00000000e+00 3.10526479e-02
  3.79941037e-04 1.00000000e+00 1.00000000e+00 3.68996131e-04
  7.12205526e-04 1.00000000e+00 1.00000000e+00 2.03471403e-06
  1.00000000e+00 1.48049506e-04 2.06302275e-04 1.00000000e+00
  5.22897787e-04 4.60432377e-07 1.00000000e+00 1.97289872e-04
  9.99994588e-01 1.00000000e+00 2.31766422e-05 7.09188181e-05
  1.5871

In [10]:
predict= np.where(predict>0.5, 1,0).reshape(1,-1)
print(predict)

[[1 1 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 0
  0 0 1 1 0 0 1 0 0 1 1 0 0 1 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0
  0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 0 0 1 1 0 1 1 0 1 0 0
  0 1 1 1 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 1 0 1 0
  0 0 0 0 0 1 0 1 1 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1
  1 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 0]]


In [11]:
from si.metrics.accuracy import accuracy

In [12]:
print(test.y)

[0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1.
 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0.
 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0.
 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0.
 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0.
 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0.
 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0.
 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]


In [13]:
score= accuracy(test.y,predict)
print(score)

0.971291866028708


# TESTING CPU

In [14]:
dataset2= read_csv("C:/Users/André Silva/SI/datasets/cpu.csv", sep=",")
dataset2.X= StandardScaler().fit_transform(dataset2.X)
train,test= train_test_split(dataset2, test_size=0.30)
train.y

array([277,  70,  84,  42,  38, 368,  92, 208,  77,  52,  76, 185,  66,
        24,  49,  32,  45,  40,  75,  36,  20,  33,  62, 140,  12, 220,
        53,  18,  56,  40, 141,  29,  60,  20,  66,  22,  61,  50,  37,
        63,  40,  21, 116, 367,  27,  25,  12,  86, 132,  32,  34, 370,
       100,  70,  50,  38,  36, 143, 510,  25, 198,  18,  22,  62,  42,
       144,  72,  30,  36,  18,  76,  12, 214,  38,  26,  30,  20, 237,
        24,  60,  74, 172,  32,  36,  32, 188,  46, 114,  62,  16, 106,
       489,  22, 189,  16,  58, 173,  66, 636, 138,  20, 109,  16,  28,
        22,  33,  45,  50, 405, 144,  26,  11,  24,  50,  46, 212,  14,
        40, 134,  33,  12,  21,  14,  80,  29,   8, 397, 269, 138, 105,
       136, 277,  13,   6,  66,  35,  44, 133,  45,  30, 113,  64,  32,
        10,  22,  60,   7], dtype=int64)

In [15]:
n=train.X.shape[1]
n

6

In [16]:
l1= Dense(input_size=n,output_size=n-2)
l2= Dense(input_size=n-2,output_size=1)

l1_sg= ReLUActivation()
l2_sg= ReLUActivation()

In [17]:
nn_model= NN(layers=[l1,l1_sg,l2,l2_sg])

In [18]:
nn_model.fit(dataset=train)

Epoch 1/1000-cost=9498.7486
Epoch 2/1000-cost=9468.2545
Epoch 3/1000-cost=9421.0638
Epoch 4/1000-cost=9350.6406
Epoch 5/1000-cost=8973.5893
Epoch 6/1000-cost=6783.9999
Epoch 7/1000-cost=1421.5464
Epoch 8/1000-cost=1190.9237
Epoch 9/1000-cost=2097.0429
Epoch 10/1000-cost=4077.9429
Epoch 11/1000-cost=8872.7750
Epoch 12/1000-cost=8621.9078
Epoch 13/1000-cost=8300.8097
Epoch 14/1000-cost=7560.8847
Epoch 15/1000-cost=3758.4632
Epoch 16/1000-cost=2915.0142
Epoch 17/1000-cost=8117.0245
Epoch 18/1000-cost=4152.8808
Epoch 19/1000-cost=1986.1025
Epoch 20/1000-cost=5689.0663
Epoch 21/1000-cost=778.5394
Epoch 22/1000-cost=809.0435
Epoch 23/1000-cost=1073.4567
Epoch 24/1000-cost=2415.1209
Epoch 25/1000-cost=3856.5460
Epoch 26/1000-cost=8802.7372
Epoch 27/1000-cost=8250.2331
Epoch 28/1000-cost=6976.7843
Epoch 29/1000-cost=2760.6497
Epoch 30/1000-cost=2446.8178
Epoch 31/1000-cost=6105.2738
Epoch 32/1000-cost=806.1800
Epoch 33/1000-cost=972.9121
Epoch 34/1000-cost=1903.2647
Epoch 35/1000-cost=3469.697

In [19]:
predict=nn_model.predict(dataset=test).reshape(1,-1)

In [20]:
predict

array([[237.29775845,  34.26665345,  30.49882282, 394.19557405,
         30.62437391, 173.77894537,  43.29499882,  38.4253149 ,
        713.62901457, 140.37939404,  58.90687303,  60.8730635 ,
         32.57918444,  42.70217956,  48.49678219,  30.49882282,
        114.51817089,  30.49882282, 107.88323509,  61.05634634,
         38.20545668,  71.69187413,  93.5594123 ,  30.49882282,
         30.49882282,  37.8954526 ,  35.05606133,  30.49882282,
         35.46408166,  90.65193876, 181.84254187,  31.60853973,
         53.54411814,  35.13188321,  30.49882282,  62.07032967,
         70.20496636, 340.62022488, 106.03822527,  37.79433871,
        345.94910713,  34.62720764, 111.63084846, 309.86000784,
        384.30384774,  33.53711269, 368.75926666,  30.49882282,
         31.71640336,  44.80206832,  40.83680509,  39.86483528,
         30.68311876,  40.94917548,  96.80047174,  58.90687303,
         30.63791327,  34.20279051, 137.07358309, 166.04757694,
         96.78215095,  57.87203623]])

In [21]:
test.y

array([ 274,   30,   22,  915,   16,  326,   72,    6, 1144,  208,   65,
        130,   52,   45,   35,   36,   51,   31,  100,  132,   50,   60,
        110,   18,   11,   50,   69,   27,   19,   41,  248,   32,   45,
         26,   16,   26,   67,  465,   38,   17,  307,   34,  214,  465,
       1150,   32,  510,   40,   24,   71,   23,   11,   24,   27,  120,
         54,   40,   17,  259,  318,   93,   71], dtype=int64)

In [22]:
score= mse(test.y,predict)
print(score)

9819.404832141005


In [23]:
from sklearn.metrics import r2_score

In [24]:
score2= r2_score(test.y,predict[0])

In [25]:
score2

0.6608830919849255