# Testing NN and Dense

In [6]:
from si.neural_netwoks.layer import *
from si.neural_netwoks.nn import NN
from si.data.dataset1 import Dataset
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# Exercício 1:

- O dataset de treino contém 32 features
- O problema é do tipo binário
- O modelo deve conter 3 Dense layers:
    * Dense layer de input
    * Dense layer com redução do número de neurónios (units) para metade
    * Dense layer final (output)
- Usa a SigmoidActivation como layer de ativação


In [7]:
#Create dataset
data_x = Dataset.from_random(64, 32, label=False)
data_x.X= StandardScaler().fit_transform(data_x.X)
y_real = np.random.RandomState(seed=0).randint(0, 2, 64)
dataset_= Dataset(X=data_x.X,y=y_real)

In [8]:
l1= Dense(input_size=32,output_size=32)
l2= Dense(input_size=32,output_size=16)
l3= Dense(input_size=16,output_size=1)
l1_sg= SigmoidActivation()
l2_sg= SigmoidActivation()
l3_sg= SigmoidActivation()

In [9]:
nn_model= NN(layers=[l1,l1_sg,l2,l2_sg,l3,l3_sg])

In [10]:
nn_model.fit(dataset=dataset_)

(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 1)
Epoch 1/1000-cost=0.1251
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 1)
Epoch 2/1000-cost=0.1252
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 1)
Epoch 3/1000-cost=0.1254
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 1)
Epoch 4/1000-cost=0.1256
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 1)
Epoch 5/1000-cost=0.1258
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 1)
Epoch 6/1000-cost=0.1260
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 1)
Epoch 7/1000-cost=0.1262
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 1)
Epoch 8/1000-cost=0.1264
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 1)
Epoch 9/1000-cost=0.1266
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 1)
Epoch 10/1000-cost=0.1267
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 1)
Epoch 11/1000-cost=0.1269
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 1)
Epoch 12/1000-cost=0.1271
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 1)
Epoch 13

In [11]:
nn_model.predict(dataset=dataset_)

(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 1)


array([[0.16497634],
       [0.16494075],
       [0.1649298 ],
       [0.16489339],
       [0.16495044],
       [0.16491114],
       [0.16496951],
       [0.16498067],
       [0.16490832],
       [0.16493423],
       [0.16495182],
       [0.16487698],
       [0.16507397],
       [0.16493561],
       [0.1649956 ],
       [0.16477501],
       [0.16499673],
       [0.16501487],
       [0.16491704],
       [0.16485097],
       [0.16486547],
       [0.16499259],
       [0.16499752],
       [0.16483695],
       [0.1647728 ],
       [0.16490884],
       [0.16481925],
       [0.16487667],
       [0.16499814],
       [0.16490916],
       [0.16492375],
       [0.16491588],
       [0.16502951],
       [0.16493159],
       [0.16496689],
       [0.16491212],
       [0.16495353],
       [0.16491426],
       [0.16494414],
       [0.16493667],
       [0.16489475],
       [0.16480003],
       [0.1649503 ],
       [0.16492981],
       [0.16489376],
       [0.16493206],
       [0.16499225],
       [0.164

# Exercício 2

 Constrói um modelo de redes neuronais 
considerando a seguinte topologia:
- O dataset de treino contém 32 features
- O problema é do tipo multiclass com 3 classes
- O modelo deve conter 3 Dense layers:
    * Dense layer de input
    * Dense layer com redução do número de neurónios (units) para metade
    * Dense layer final (output)
- Usa a SigmoidActivation como layer de ativação
- Usa a SoftMaxActivation como última layer de ativação

In [24]:
#Create dataset
data_x = Dataset.from_random(64, 32, label=False)
y_real = np.random.RandomState(seed=0).randint(0, 3, 64)
dataset_= Dataset(X=data_x.X,y=y_real)

In [25]:

l1= Dense(input_size=32,output_size=32)
l2= Dense(input_size=32,output_size=16)
l3= Dense(input_size=16,output_size=3)
l1_sg= SigmoidActivation()
l2_sg= SigmoidActivation()

In [26]:
nn_model= NN(layers=[l1,l1_sg,l2,l2_sg,l3])
nn_model.fit(dataset=dataset_)

(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 3)
(16, 3)
(16, 64)
(64, 3)
(32, 16)
(32, 64)
(64, 16)
(32, 32)
(32, 64)
(64, 32)
Epoch 1/1000-cost=2.2556
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 3)
(16, 3)
(16, 64)
(64, 3)
(32, 16)
(32, 64)
(64, 16)
(32, 32)
(32, 64)
(64, 32)
Epoch 2/1000-cost=2.1286
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 3)
(16, 3)
(16, 64)
(64, 3)
(32, 16)
(32, 64)
(64, 16)
(32, 32)
(32, 64)
(64, 32)
Epoch 3/1000-cost=2.0159
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 3)
(16, 3)
(16, 64)
(64, 3)
(32, 16)
(32, 64)
(64, 16)
(32, 32)
(32, 64)
(64, 32)
Epoch 4/1000-cost=1.9158
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 3)
(16, 3)
(16, 64)
(64, 3)
(32, 16)
(32, 64)
(64, 16)
(32, 32)
(32, 64)
(64, 32)
Epoch 5/1000-cost=1.8265
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 3)
(16, 3)
(16, 64)
(64, 3)
(32, 16)
(32, 64)
(64, 16)
(32, 32)
(32, 64)
(64, 32)
Epoch 6/1000-cost=1.7469
(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 3)
(16, 

In [27]:
nn_model.predict(dataset=dataset_)

(64, 32)
(64, 32)
(64, 32)
(64, 16)
(64, 16)
(64, 3)


array([[0.88317595, 0.88306711, 0.8832539 ],
       [0.88317618, 0.88306734, 0.88325413],
       [0.88317479, 0.88306595, 0.88325274],
       [0.88317331, 0.88306445, 0.88325126],
       [0.88317227, 0.88306341, 0.88325022],
       [0.88317629, 0.88306745, 0.88325424],
       [0.88317564, 0.8830668 , 0.88325359],
       [0.883176  , 0.88306716, 0.88325395],
       [0.88317354, 0.88306469, 0.88325149],
       [0.8831766 , 0.88306776, 0.88325454],
       [0.88317607, 0.88306723, 0.88325401],
       [0.88317559, 0.88306674, 0.88325353],
       [0.88317655, 0.88306771, 0.8832545 ],
       [0.88317652, 0.88306767, 0.88325446],
       [0.88317604, 0.8830672 , 0.88325399],
       [0.8831756 , 0.88306676, 0.88325355],
       [0.88317657, 0.88306772, 0.88325451],
       [0.88317619, 0.88306735, 0.88325413],
       [0.88317472, 0.88306587, 0.88325267],
       [0.88317632, 0.88306748, 0.88325426],
       [0.88317655, 0.88306771, 0.8832545 ],
       [0.88317624, 0.88306739, 0.88325418],
       [0.

# Exercício 3
Constrói um modelo de redes neuronais 
considerando a seguinte topologia:
- O dataset de treino contém 32 features
- O problema é do tipo regressão
- O modelo deve conter 3 Dense layers:
   * Dense layer de input
   * Dense layer com redução do número de neurónios (units) para metade
   * Dense layer final (output)
- Usa a ReLU como layer de ativação
- Considera que o modelo deve acabar com uma ativação linear

In [32]:
#Create dataset
data_x = Dataset.from_random(200, 32, label=False)
y_real = np.random.RandomState(seed=0).randn(200,1)
dataset_= Dataset(X=data_x.X,y=y_real)

In [33]:

l1= Dense(input_size=32,output_size=32)
l2= Dense(input_size=32,output_size=16)
l3= Dense(input_size=16,output_size=2)
l1_sg= ReLUActivation()
l2_sg= ReLUActivation()

In [34]:
nn_model= NN(layers=[l1,l1_sg,l2,l2_sg,l3])
nn_model.fit(dataset=dataset_)

(200, 32)
(200, 32)
(200, 32)
(200, 16)
(200, 16)
(200, 2)
(16, 2)
(16, 200)
(200, 2)
(32, 16)
(32, 200)
(200, 16)
(32, 32)
(32, 200)
(200, 32)
Epoch 1/1000-cost=1.0483
(200, 32)
(200, 32)
(200, 32)
(200, 16)
(200, 16)
(200, 2)
(16, 2)
(16, 200)
(200, 2)
(32, 16)
(32, 200)
(200, 16)
(32, 32)
(32, 200)
(200, 32)
Epoch 2/1000-cost=1.0482
(200, 32)
(200, 32)
(200, 32)
(200, 16)
(200, 16)
(200, 2)
(16, 2)
(16, 200)
(200, 2)
(32, 16)
(32, 200)
(200, 16)
(32, 32)
(32, 200)
(200, 32)
Epoch 3/1000-cost=1.0481
(200, 32)
(200, 32)
(200, 32)
(200, 16)
(200, 16)
(200, 2)
(16, 2)
(16, 200)
(200, 2)
(32, 16)
(32, 200)
(200, 16)
(32, 32)
(32, 200)
(200, 32)
Epoch 4/1000-cost=1.0480
(200, 32)
(200, 32)
(200, 32)
(200, 16)
(200, 16)
(200, 2)
(16, 2)
(16, 200)
(200, 2)
(32, 16)
(32, 200)
(200, 16)
(32, 32)
(32, 200)
(200, 32)
Epoch 5/1000-cost=1.0479
(200, 32)
(200, 32)
(200, 32)
(200, 16)
(200, 16)
(200, 2)
(16, 2)
(16, 200)
(200, 2)
(32, 16)
(32, 200)
(200, 16)
(32, 32)
(32, 200)
(200, 32)
Epoch 6/100

In [35]:
nn_model.predict(dataset=dataset_)

(200, 32)
(200, 32)
(200, 32)
(200, 16)
(200, 16)
(200, 2)


array([[0.0709332 , 0.07089182],
       [0.07090057, 0.0709019 ],
       [0.07090348, 0.07089521],
       [0.0708873 , 0.07091567],
       [0.0709152 , 0.07089851],
       [0.07090015, 0.07091526],
       [0.07092049, 0.07089621],
       [0.07089676, 0.07091788],
       [0.07089628, 0.07092297],
       [0.0709072 , 0.07090247],
       [0.0708899 , 0.07090473],
       [0.07091132, 0.07090053],
       [0.0709226 , 0.0709072 ],
       [0.07091446, 0.07091263],
       [0.07091148, 0.07092019],
       [0.07090303, 0.07091606],
       [0.07089485, 0.07091215],
       [0.07090544, 0.07090411],
       [0.0709189 , 0.07092133],
       [0.07092297, 0.07089451],
       [0.07088366, 0.07091976],
       [0.07091958, 0.07090922],
       [0.07088662, 0.07092004],
       [0.0709258 , 0.07090758],
       [0.07091265, 0.07090338],
       [0.07088939, 0.07093671],
       [0.07092832, 0.07088647],
       [0.07092099, 0.07088132],
       [0.07092   , 0.07089697],
       [0.07092407, 0.0709035 ],
       [0.